app:
  topPlayersLimit: 5
  minGames: 30
  winPoints: 25
  winShutoutPoints: 50
  losePoints: -25
  loseShutoutPoints: -50
  algorithm: "PERCENTAGE"

db:
  host: "127.0.0.1"
  port: 3306
  database: "cata"
  username: "root"
  password: "password"

rabbit:
  global:
    username: "rabbitmq"
    password: "rabbitmq"
    host: "localhost"
    virtualHost: "ukl"
    port: 5672
    exchange: "ukl_exchange"
  listPlayersQueue:
    name: "listPlayersQueue"
    key: "list_players"
  addPlayerQueue:
    name: "addPlayerQueue"
    key: "add_player"
  errorsQueue:
    name: "errorsQueue"
    key: "errors"

server:
  port: 8080