app:
  topPlayersLimit: 5
  winPoints: 25
  winShutoutPoints: 50
  losePoints: -25
  loseShutoutPoints: -50

db:
  host: "127.0.0.1"
  port: 3306
  database: "cata"
  username: "root"
  password: "password"