version: 2
jobs:
  build:
    working_directory: ~/repo
    environment:
      IMAGE_NAME: utfstats
      JVM_OPTS: -Xmx3200m
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/buildpack-deps:stretch
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
            apt update && apt install -y curl
            curl -L -o sbt-1.3.8.deb https://dl.bintray.com/sbt/debian/sbt-1.3.8.deb
            dpkg -i sbt-1.3.8.deb
            rm sbt-1.3.8.deb
            apt-get update
            apt-get install -y sbt python-pip git
            pip install awscli
            apt-get clean && apt-get autoclean
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
      - run:
          name: SBT CLEAN
          command: cat /dev/null | sbt clean
      - run:
          name: SBT COMPILE
          command: cat /dev/null | sbt compile
      - run:
          name: Make JAR
          command: cat /dev/null | sbt assembly
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  publish-latest:
    environment:
      IMAGE_NAME: building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: /release.*/
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: /release.*/