version: '2'
services:
  catamysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=cata
      - MYSQL_ROOT_PASSWORD=password
  catamongo:
    image: mongo:4.0
    container_name: fbcoremongo
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 2
    ports:
      - "27017:27017"
  catarabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "ukl"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "ukl_rabbit"
