version: '3.3'
services:
#  catamysql:
#    image: mysql
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_DATABASE=cata
#      - MYSQL_ROOT_PASSWORD=password
  catamongo:
    image: mongo:latest
    container_name: catamongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: cata
      MONGO_INITDB_USERNAME: root
      MONGO_INITDB_PASSWORD: password
  catarabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "ukl"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "ukl_rabbit"
