version: '2'
services:
  mysql:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=cata
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=admin
